### ISSUE TITLE
[BUG] Time delay

### ISSUE THREAD

**Issue by ElMoha943** [Pulsih/BankPlus#1]
Time delay isnt working for me, i set it in 15m but it still does it every 5m as default.
Running Tuinity version git-Tuinity-"9f3435b" (MC: 1.16.5)

![image](https://user-images.githubusercontent.com/25410859/125501582-be499948-b1d5-4867-8dd6-235e2dc315ea.png)

Also i think theres an error here: `Money-Given: "0.05" # 2% of the bank amount` isnt that 5%?

**Comment by Pulsih** [comment]
No, the mechanics about the % of the interest have been changed, and now 5% is 0.05%, also i don't know what you mean with Time Delay not working, did you try running the command /bank interest restart?

**Comment by ElMoha943** [comment]
> No, the mechanics about the % of the interest have been changed, and now 5% is 0.05%

I meant the comment in config says taht 0.05 is 2%, just a detail.

> also i don't know what you mean with Time Delay not working, did you try running the command /bank interest restart?

Ah i did and it works now, i thought that /bankplus restart would cover that. Sorry

**Comment by Pulsih** [comment]
> > No, the mechanics about the % of the interest have been changed, and now 5% is 0.05%
> 
> I meant the comment in config says thatt 0.05 is 2%, just a detail.
> 
> > also i don't know what you mean with Time Delay not working, did you try running the command /bank interest restart?
> 
> Ah i did and it works now, i thought that /bankplus restart would cover that. Sorry

No problem, glad to be helpfull, and thanks for the bug report! <3
