### ISSUE TITLE
Geyser exit bug

### ISSUE THREAD

**Issue by hitanol** [Pulsih/BankPlus#11]
I'm trying to type exit to exit the custom withdraw or deposit but it's being parsed as number I think

![Screenshot_20220511-074050_Minecraft](https://user-images.githubusercontent.com/99027279/167852352-489a7b08-f222-4672-bac0-04bb0a3b959f.png)

**Comment by Pulsih** [comment]
No support here

**Comment by hitanol** [comment]
open it, happens in java too lol

**Comment by hitanol** [comment]
there is another bug too, when u dont have money to deposit or withdraw theres a weird message that there is not in messages config file and i think its supposed to be Insufficient-Money-Withdraw and Insufficient-Money-Deposit

preview https://fs-01.cyberdrop.to/2022-05-23%2021-28-01-urRXFa6e.mkv
