### ISSUE TITLE
[SUGGESTION] Ability to disable chat messages

### ISSUE THREAD

**Issue by ElMoha943** [Pulsih/BankPlus#2]
I would like the ability to disable the message everytime you get interests.

**Comment by Pulsih** [comment]
You can already do it

**Comment by ElMoha943** [comment]
how? i dont see the option in config

**Comment by Pulsih** [comment]
In messages.yml, you can find Interest-Broadcast, then the option Enabled

**Comment by ElMoha943** [comment]
> In messages.yml, you can find Interest-Broadcast, then the option Enabled, if you put it to false, players won't receive the Interest message, hope that helped

I see, i suggest you change the enable/disable part to the config.yml, messages.yml its usually just for translating purpose. Thanx you.

**Comment by Pulsih** [comment]
> > In messages.yml, you can find Interest-Broadcast, then the option Enabled, if you put it to false, players won't receive the Interest message, hope that helped
> 
> I see, i suggest you change the enable/disable part to the config.yml, messages.yml its usually just for translating purpose. Thanx you.

I am sorry, but the "true", "false" options are by default, its called "boolean", editing it will mean complex the code, i will see if edit it in the future, thank you!

**Comment by ElMoha943** [comment]
> I am sorry, but the "true", "false" options are by default, its called "boolean"

Oh yeh i know that, i just mean that you should move this part:

```yml
Title-Custom-Amount:
  Enabled: true
  
Interest-Broadcast:
  Enabled: false
```

to config.yml as its a configuration value and not a message to translate.
