### ISSUE TITLE
1.12.2 Invalid SoundType Error, Invalid-Number Error and SUGGESTION

### ISSUE THREAD

**Issue by TeQTabanca** [Pulsih/BankPlus#7]
### Invalid SoundType Error

- [08:59:12 INFO]: BankPlus Invalid SoundType at: General.Personal-Sound.Sound
- [08:59:20 INFO]: BankPlus Invalid SoundType at: General.Withdraw-Sound.Sound

### Invalid-Number Error

![I have 500 money in the bank](https://user-images.githubusercontent.com/89253304/148676501-eed4fec2-d504-4696-aa1f-7c10bcd84e20.png)

![Withdraw](https://user-images.githubusercontent.com/89253304/148676514-0db8f48b-f7a3-4dc1-a7be-195d82916ed1.png)

![I'm trying to withdraw 500 money from the bank](https://user-images.githubusercontent.com/89253304/148676522-718ab2d9-6e8e-444a-b22f-78135b657fe3.png)

![but i am getting error](https://user-images.githubusercontent.com/89253304/148676555-f36834de-2708-4a50-abf6-7f34069959c4.png)

### SUGGESTION

**How about we write the private withdrawal transaction on the sign?**

### EXAMPLE:

![How much money do you want to withdraw](https://user-images.githubusercontent.com/89253304/148677393-bcc22d67-92f1-42cd-8f9d-eca9572dd99e.png)

**Comment by VoChiDanh** [comment]
try /bank withdraw/deposit

**Comment by TeQTabanca** [comment]
![bank withdraw 500](https://user-images.githubusercontent.com/89253304/148684779-1eb78e80-7b09-4718-b108-4a3fcf29a934.png)

![Succesfully Withdraw 500](https://user-images.githubusercontent.com/89253304/148684880-94b328c7-05cd-4c7d-aea0-290321ab4c5c.png)


![bank deposit 500](https://user-images.githubusercontent.com/89253304/148684796-edec0b80-46da-4adc-b9e7-129ef02fb861.png)

![Succesfully Deposit 500](https://user-images.githubusercontent.com/89253304/148684809-3fcb2f30-aaa3-400e-a3e7-e02c0f42c960.png)

**Comment by Pulsih** [comment]
First of all [08:59:12 INFO]: BankPlus Invalid SoundType at: General.Personal-Sound.Sound its not an error, YOU have to manage YOURSELF to edit sounds and make them compatible with your server

The sign feature does not exit on BankPlus

The invalid number problem its a compatibility problem, check if you have any chat plugins like InteractiveChat

**Comment by TeQTabanca** [comment]
**I use InteractiveChat and VentureChat plugins.**

**Comment by VoChiDanh** [comment]
![image](https://user-images.githubusercontent.com/86956269/148685434-f246e24d-17b4-4a3a-8c0e-d724204bd38a.png)

**Comment by Pulsih** [comment]
> ![image](https://user-images.githubusercontent.com/86956269/148685434-f246e24d-17b4-4a3a-8c0e-d724204bd38a.png)

Thank you VoChiDanh

**Comment by TeQTabanca** [comment]
### It worked. Thanks.

**Comment by Pulsih** [comment]
Next time use the discord to get support
