### ISSUE TITLE
Bank interest scheduling [Feature Request]

### ISSUE THREAD

**Issue by antjparsons** [Pulsih/BankPlus#8]
Each time we restart our server, the interest cooldown gets knocked out of time. Restarting the cooldown often means players miss out on interest.

We want it to run every hour on the hour, or daily at midnight or midday (real life hour/daily, not in-game). This would just be based on the physical server's system time (or whatever is available to a Minecraft server/spigot).

Would it be possible to add additional options for when interest is given to players?

Otherwise very happy with the plugin!

**Comment by Pulsih** [comment]
No suggestions here
